export const data = [
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
    {
      id: "TASK-8782",
      Name: "CAFETTOID-95",
      Role: " Admin",
      STORE: "documentation",
      Mac: "documentation",
      Email: "mohamedabdelghany937@gmail.com	",
      PHONE: "0512357465	",
      ADDRESS: "mohamedabdelghany937@gmail.com	",
      BIRTH: "September 12, 2024 12:11 PM",
      GENDER: "Male",
      ACTIVATION: "Active",
      VACATION: "Working",
      CREATED: "September 12, 2024 12:11 PM",
    },
  ];
  